### ISSUE TITLE
Stage II of munging

### ISSUE THREAD

**Issue by achafetz** [USAID-ICPI/weekend_special#4]
for each Partner's Google Sheet:
- read in each sheet
- reshape
- adjust date
- add variable name
- append to other indicator sheets

then need to append each file to other partner files

**Comment by jaliasd** [comment]
@achafetz Each partners' sheet is structured slightly differently. I have a macro that'll pull the sheet names from any individual sheet, but would rather that it pull from all the sheets to one place.

`Sub GetSheets()
    Dim w As Worksheet
    Dim iRow As Integer
    Dim iCol As Integer

    iRow = Selection.Row
    iCol = Selection.Column
    For Each w In Worksheets
        Cells(iRow, iCol) = w.Name
        iRow = iRow + 1
    Next w
End Sub
`

**Comment by jaliasd** [comment]
Another issue: The tab names are not consistant across partners. This screen shot is a pivot off of the weekend_special_mapping.xlsx 

![image](https://user-images.githubusercontent.com/8836685/39399029-9a27728a-4ae4-11e8-95a8-5d9d9affaf7b.png)

Compared to this list of indicators reported on in the "Collated weekend reports - DCM -merged.xlsx" sent by Mavis on 4/19. 

![image](https://user-images.githubusercontent.com/8836685/39399040-c6ed9d08-4ae4-11e8-88d0-5d5099c2cd2e.png)

So how do we get to that list from the worksheets available? Do we try and reverse engineer or ask the team?

**Comment by achafetz** [comment]
Good inspection! (You should save the VBA code and put in in a VBA folder.  Copy the VBA to sublime/atom and save it as a a `.bas` file.)

We can do this on the backend  with our scripts BUT since we're dealing with Google Sheets, this should be really easy to fix. It would be ideal if every template has the exact same structure and I don't see any reason why they shouldn't be.

We should discuss template uniformity with Mavis et al this week.

**Comment by achafetz** [comment]
closing but @jaliasd issues relate to #12
